import { Drawer } from "vaul";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function HelpDrawer({ open, onOpenChange }: Props) {
  return (
    <Drawer.Root direction="right" open={open} onOpenChange={onOpenChange}>
      <Drawer.Portal>
        <Drawer.Overlay className="fixed inset-0 bg-black/40 z-50" />
        <Drawer.Content className="fixed top-0 right-0 bottom-0 w-[480px] z-50 bg-bg-surface border-l border-white/10 outline-none flex flex-col">
          <div className="p-5 border-b border-white/5">
            <Drawer.Title className="text-lg font-bold text-text-primary">How to Play</Drawer.Title>
            <Drawer.Description className="text-xs text-text-muted">
              Your guide to becoming a 10x engineer
            </Drawer.Description>
          </div>

          <div className="flex-1 overflow-y-auto p-5 space-y-5 text-sm text-text-secondary">
            <Section title="The Basics" icon="👋">
              <p>
                Click the <strong>code editor</strong> in the center to write lines of code (LoC). Each click produces
                LoC based on your current click power.
              </p>
              <p>
                LoC is your currency -- spend it to hire developers and buy upgrades that generate code automatically.
              </p>
            </Section>

            <Section title="Buildings" icon="🏗️">
              <p>
                Buildings produce LoC passively every second. There are 12 buildings that unlock as you earn more total
                LoC. Each building can be owned up to <strong>500</strong> times.
              </p>
              <ul className="list-none space-y-1 mt-2">
                <li>
                  ☕ <strong>Intern</strong> -- 0.2 LoC/s
                </li>
                <li>
                  💻 <strong>Junior Developer</strong> -- 8 LoC/s
                </li>
                <li>
                  🧑‍💻 <strong>Senior Developer</strong> -- 100 LoC/s
                </li>
                <li>
                  📊 <strong>Data Scientist</strong> -- 1,200 LoC/s
                </li>
                <li>
                  🔧 <strong>DevOps Engineer</strong> -- 15,000 LoC/s
                </li>
                <li>
                  🤖 <strong>AI Coding Assistant</strong> -- 200,000 LoC/s
                </li>
                <li>
                  📐 <strong>Tech Lead</strong> -- 3,000,000 LoC/s
                </li>
                <li>
                  🖥️ <strong>Server Farm</strong> -- 50,000,000 LoC/s
                </li>
                <li>
                  ☁️ <strong>Cloud Architect</strong> -- 1,000,000,000 LoC/s
                </li>
                <li>
                  🌐 <strong>Open Source Community</strong> -- 25B LoC/s
                </li>
                <li>
                  ⚛️ <strong>Quantum Computing Lab</strong> -- 500B LoC/s
                </li>
                <li>
                  🌌 <strong>Galactic Dev Network</strong> -- 10T LoC/s
                </li>
              </ul>
              <p className="mt-2">
                Each building costs more as you buy more (1.15x per unit). Use <strong>Buy x1/x10/x100/Max</strong> to
                bulk purchase.
              </p>
            </Section>

            <Section title="Technical Debt" icon="💳">
              <p>
                Every building generates Tech Debt proportional to its output. Cheap buildings (Interns, Junior Devs)
                write sloppy code with high debt. The TD penalty <strong>scales with your production rate</strong> --
                roughly 15 seconds worth of accumulated TD gives ~50% penalty.
              </p>
              <p className="mt-2">
                <strong className="text-accent-green">Debt cleaners:</strong> Senior Dev, DevOps, Tech Lead, Cloud
                Architect all have <strong>negative</strong> TD ratios -- they actively reduce debt. Upgrading them
                boosts both production AND cleanup rate.
              </p>
              <p className="mt-1">
                <strong>Refactor:</strong> Click "Refactor" in the top bar to remove <strong>70%</strong> of current TD.
                Pauses production for 10 seconds.
              </p>
              <p className="mt-1">
                <strong>TD Reduction upgrades:</strong> Reduce the debt generated by specific buildings (e.g., "Linter
                for Interns" reduces Intern TD by 30%).
              </p>
              <p className="mt-1 text-accent-pink text-xs">
                Tip: Peak Tech Debt during a run gives up to +10% bonus reputation when you prestige!
              </p>
            </Section>

            <Section title="Bugs" icon="🐛">
              <p>When Tech Debt is high relative to production, bugs spawn on screen. Up to 3 at once at high debt.</p>
              <ul className="list-none space-y-1 mt-2">
                <li>
                  <span className="text-green-400">Minor</span> (green) -- Small penalty. 10s to fix.
                </li>
                <li>
                  <span className="text-orange-400">Major</span> (orange) -- Moderate penalty. Memory Leak drains LoC,
                  Infinite Loop pauses a building. 8s to fix.
                </li>
                <li>
                  <span className="text-red-400">Critical</span> (red) -- Severe penalty if missed: Segfault freezes
                  production, Production Outage doubles TD, Security Vulnerability causes massive LoC loss. 6s to fix.
                </li>
              </ul>
              <p className="mt-2 text-xs text-text-muted">
                Fix bugs for LoC rewards + TD reduction. Higher TD = more and deadlier bugs.
              </p>
            </Section>

            <Section title="Hacks" icon="🍝">
              <p>
                Temporary boosts that add Tech Debt. Unlock at LoC milestones. Requires your TD to be below a threshold
                to activate. TD costs scale with your current production.
              </p>
              <ul className="list-none space-y-1 mt-2">
                <li>
                  🍝 <strong>Spaghetti Sprint</strong> -- 1.5x production for 45s
                </li>
                <li>
                  📋 <strong>Copy-Paste Frenzy</strong> -- 5x click power for 30s
                </li>
                <li>
                  🧊 <strong>Code Freeze</strong> -- TD stops accumulating for 30s
                </li>
                <li>
                  🛡️ <strong>Bug Shield</strong> -- No bugs spawn for 45s
                </li>
                <li>
                  📦 <strong>Dependency Hell</strong> -- Instant 30s of production
                </li>
              </ul>
              <p className="mt-2 text-accent-pink text-xs">
                Hacks have radial cooldown timers. Manage your TD to keep them available!
              </p>
            </Section>

            <Section title="Upgrades" icon="⬆️">
              <p>One-time LoC purchases that permanently boost production:</p>
              <ul className="list-disc list-inside space-y-1 mt-2">
                <li>
                  <strong>Building upgrades</strong> at counts 10, 25, 50, 75, 100, 125, 150, 175, 200, 250, 300, 400,
                  500. Each gives 2x-5x production.
                </li>
                <li>
                  <strong>Cross-building upgrades</strong> -- one building's count boosts another (e.g., "25 Senior
                  Devs: 2x Junior Dev production").
                </li>
                <li>
                  <strong>Code quality upgrades</strong> -- boost cleaner buildings at LoC milestones.
                </li>
                <li>
                  <strong>TD reduction upgrades</strong> -- reduce debt generation for specific buildings.
                </li>
                <li>
                  <strong>Click upgrades</strong> at click milestones.
                </li>
                <li>
                  <strong>CPS-to-Click</strong> -- adds a % of LoC/sec to each click.
                </li>
              </ul>
              <p className="mt-2 text-accent-cyan text-xs">
                Use "Buy All Affordable" to purchase all cheap upgrades at once!
              </p>
            </Section>

            <Section title="Mastery & Victory" icon="👑">
              <p>
                When a building reaches <strong>500 count</strong> with all 13 standard upgrade tiers purchased, it
                achieves <strong className="text-accent-green">Mastery</strong> -- a permanent <strong>10x</strong>{" "}
                production bonus shown as a green badge.
              </p>
              <p className="mt-2">
                <strong>Master all 12 buildings</strong> to beat the game and see the Victory screen with your final
                stats!
              </p>
            </Section>

            <Section title="Prestige -- Ship the Product" icon="📦">
              <p>
                Once you've earned <strong>1,000,000 total LoC</strong> in a run, you can{" "}
                <strong>Ship the Product</strong>:
              </p>
              <ul className="list-disc list-inside space-y-1 mt-2">
                <li>Resets your LoC, buildings, upgrades, Tech Debt, and Hacks</li>
                <li>Earns Reputation Points (logarithmic scaling)</li>
                <li>Each reputation point gives +1% to all production permanently</li>
              </ul>
              <p className="mt-2">
                Spend reputation on <strong>Prestige Upgrades</strong> -- permanent bonuses like starting LoC, cost
                reduction, free buildings, and production multipliers.
              </p>
            </Section>

            <Section title="Random Buffs" icon="🔥">
              <p>Glowing orbs spawn every 45-120 seconds. Click before they fade (10s):</p>
              <ul className="list-none space-y-1 mt-2">
                <li>
                  🔥 <strong>Code Frenzy</strong> -- 1.5x production for 30s
                </li>
                <li>
                  ⚡ <strong>Click Storm</strong> -- 10x click power for 20s
                </li>
                <li>
                  🍀 <strong>Lucky Commit</strong> -- instant 30s of production
                </li>
                <li>
                  💻 <strong>Hackathon Weekend</strong> -- 1.25x production for 60s
                </li>
                <li>
                  🎉 <strong>Merge Party</strong> -- instant 2 min of production
                </li>
              </ul>
            </Section>

            <Section title="Saving" icon="💾">
              <p>Auto-saves every 30 seconds and on tab close. Offline progress for up to 8 hours.</p>
            </Section>
          </div>
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
}

function Section({ title, icon, children }: { title: string; icon: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="flex items-center gap-2 text-base font-semibold text-text-primary mb-2">
        <span>{icon}</span> {title}
      </h3>
      <div className="space-y-2 text-text-secondary leading-relaxed">{children}</div>
    </div>
  );
}
